# Generated by Django 5.2.5 on 2025-08-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedback_remove_profile_profile_pic_profile_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
