# Generated by Django 5.2.5 on 2025-08-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile_number',
        ),
    ]
