# Generated by Django 5.2.5 on 2025-08-22 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_profile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.payment'),
            preserve_default=False,
        ),
    ]
