# Generated by Django 5.2.5 on 2025-08-22 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_feedback_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('details', models.TextField()),
                ('amount', models.TextField()),
                ('deadline', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comittee'),
        ),
    ]
