# Generated by Django 5.2.5 on 2025-08-23 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comittee_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comittee',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
