# Generated by Django 5.2.5 on 2025-08-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_payment_feedback_alter_comittee_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Feedback',
            new_name='feedback',
        ),
    ]
