# Generated by Django 5.2.5 on 2025-08-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_feedback_payment_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
