# Generated by Django 5.2.5 on 2025-09-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='semester',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
