# Generated by Django 5.2.5 on 2025-09-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_payment_amount_payment_comittee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='payments',
        ),
        migrations.AddField(
            model_name='payment',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Comittee',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
