# Generated by Django 5.2.5 on 2025-09-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_payment_payment_type_remove_feedback_payments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.TextField(blank=True, default='Pending', null=True),
        ),
    ]
