# Generated by Django 5.2.7 on 2025-11-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_payment_cf_payment_lac_payment_pta_payment_qaa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='school_year',
            field=models.TextField(blank=True, null=True),
        ),
    ]
