# Generated by Django 5.2.7 on 2025-11-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_paymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_walk_in',
            field=models.BooleanField(default=False),
        ),
    ]
